[project]
name = "advent-of-code-2025"
description = "Advent of Code 2025"
version = "0.0.0"
authors = [
    { name = "Keith Ma", email = "keithfma@gmail.com" }
]
dependencies = [
    "ipython>=9.7.0",
    "networkx>=3.6.1",
    "numpy>=2.3.5",
    "scipy>=1.16.3",
]
